Repository hypermystic/bookit, pull requests merged in 2020-10, with the labels that each got.

#1 Basic Scaffold
  .firebase/hosting.YnVpbGQ.cache
  .firebase/hosting.cHVibGlj.cache
  .firebaserc
  .gitignore
  README.md
  firebase.json
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/Profile.js
  src/Signup.css
  src/Signup.js
  src/index.css
  src/index.js
  src/logo.svg
  src/setupTests.js
Labels: hacktoberfest-accepted

#14 Add google analytics
  README.md
  public/index.html
Labels: hacktoberfest-accepted

#21 Added the error 404 page and hooked it up with React Router to the in…
  src/Error404.css
  src/Error404.js
  src/index.js
Labels: Under Review, hacktoberfest-accepted, request-changes

#24 Feat: add ctrl + s functionality for saving the file
  src/App.js
Labels: Under Review, hacktoberfest-accepted
